version: '3'
services:
  influxdb:
    image: "influxdb:latest"
    hostname: "influxdb"
    networks:
      tik_net:
    volumes:
      - "./var/lib/influxdb:/var/lib/influxdb"
      - "./var/log/influxdb:/var/log/influxdb"
    ports:
      - "8086:8086"
    expose:
      - "8086"
  telegraf:
    image: "telegraf:latest"
    hostname: "telegraf"
    networks:
      tik_net:
    volumes:
      - "./etc/telegraf:/etc/telegraf"
      - "./var/log/telegraf:/var/log/telegraf"
  chronograf:
    image: "chronograf:latest"
    hostname: "chronograf"
    networks:
      tik_net:
    volumes:
      - "./var/lib/chronograf:/var/lib/chronograf"
      - "./var/log/chronograf:/var/log/chronograf"
    ports:
      - "8888:8888"
  kapacitor:
    image: "kapacitor:latest"
    hostname: "kapacitor"
    networks:
      tik_net:
    volumes:
      - "./var/lib/kapacitor:/var/lib/kapacitor"
      - "./etc/kapacitor:/etc/kapacitor"
      - "./var/log/kapacitor:/var/log/kapacitor"

networks:
  tik_net:
    driver: bridge
